### ISSUE TITLE
The Achievement's descriptions are coming out as the file destination or are missing completely making it hard to play and progress through the pack  

### ISSUE THREAD

**Issue by Nat407** [misterplus/Levitated#100]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by misterplus** [comment]
Redownload the pack and make sure there's a resource folder, don't download the serverpack, that doesn't have every single file needed for the client.

**Comment by Nat407** [comment]
Thanks man.
