### ISSUE TITLE
Bug with Mattock

### ISSUE THREAD

**Issue by Mixakas** [misterplus/Levitated#102]
## Bug Description

 Chopping a Wyrmwood Log with Mattock (a tool frm Tinker's Construct) doesn't give any items (Wyrmwood logs). It should be registered as an axe and Waila (pretty sure this isn't that mod but a similar one) shows this tool as an axe.

### Did this behavior use to work in the previous version?

 Only played the latest version so not sure

## Steps to Reproduce (for bugs)

1. Make an End Mattock
2. Break a Wyrmwood log with it
3. No item drops

## Logs

* Client/Server Log: Game doesn't crash so I have no logs
* Crash Log: Game doesn't crash so I have no logs

## Client Information
* Modpack Version: Latest (1.5.2)
* Java Version: Latest
* Launcher Used: CurseForge
* Memory Allocated: About 10Gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: Latest version (1.5.2)
* Additional Content Installed: No additional content

**Comment by misterplus** [comment]
Duplicated with #90
