### ISSUE TITLE
spawns me in void on start

### ISSUE THREAD

**Issue by dexter101555** [misterplus/Levitated#105]
no crash

## Client Information
* 1.12.2
* 1.12.2:
* minecraft:
* i dont know what this means sorry:
* im alone
* no:
* i do not Enabled:

## World Information
* 1.12.2:
*none
![2021-01-23_20 56 40](https://user-images.githubusercontent.com/77910533/105621582-d3e2f280-5dbd-11eb-878e-8e56209a551d.png)

**Comment by dexter101555** [comment]
please i need help with this it wont let me play the modpack

**Comment by misterplus** [comment]
You'll need to download the client pack instead of the serverpack, you're missing certain files that makes you spawn in the end.
So in short, just redownload the pack.
