### ISSUE TITLE
在重构之前主世界已有地形 The Overworld already had a terrain without rebuilding it

### ISSUE THREAD

**Issue by 65550094** [misterplus/Levitated#106]
## Bug描述

使用彩虹石建造主世界传送门后主世界自动刷新地形而非虚空
The Overworld already had terrains but not the void after building a portal by the Rainbow stone.

### 在之前的版本中出现过此问题吗？

我不确定，我的服务器在建造传送门之前才升了个版本(1.5.1->1.5.2)
I'm not sure. Because my server upgraded the version from 1.5.1 to 1.5.2 before I build the portal.

## 重现Bug的步骤

1.使用彩虹桥方块造一个传送门然后用法杖激活它
Use the Rainbow-Bridge stone to build a portal and activate it.
2.进入传送门并传回主世界
Get into the portal and teleport to the overworld.
3.几秒钟过后主世界自动刷新地形
The Overworld will build the terrain automatically after a few seconds.

## 日志

* 客户端/服务端日志:
* 崩溃报告:
No crash here.

## 客户端信息
* 模组包版本:1.5.2
* Java版本:Java8 64bit 241
* 启动器:Plain Craft Launcher 2
* 分配内存:服务器4G 客户端4G Server 4096 MB and Client 4096 MB
* 服务器/局域网/单人游戏:服务器 Server
* 是否安装Optifine:否 No
* 是否安装光影:否 No

## 世界信息
* 创建世界时的模组包版本:1.5.1
* 安装的其他模组等额外内容:无 None

**Comment by misterplus** [comment]
请确认level-type为void_plustweaks
这是官方服务端的默认设置。

**Comment by 65550094** [comment]
> 请确认level-type为void_plustweaks
> 这是官方服务端的默认设置。

level-type始终是void_plustweaks没变过

**Comment by misterplus** [comment]
建议二次检查存档本身的level-type，在level.dat文件里面
