### ISSUE TITLE
Unable to craft chaos pearls

### ISSUE THREAD

**Issue by Aciho** [misterplus/Levitated#108]
## Bug Description

The chaos pearl recipe has stopped working. I could craft them for a while but now when I try there is no output shown for the recipe. If I try in a crafting table it shows the output but doesn't actually craft them.

### Did this behavior use to work in the previous version?

Haven't played any previous versions

## Steps to Reproduce (for bugs)

1. Try to craft chaos pearl
2. Can't help with the repro beyond that I'm afraid
3. Sorry

## Logs

* Client/Server Log:
* Crash Log: https://gist.github.com/Aciho/074e52daa062d2609f132d5d4fcc723e

## Client Information
* Modpack Version: 1.5.2
* Java Version: 1.8.0_242
* Launcher Used: GDLauncher
* Memory Allocated: 5632mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 1.5.2
* Additional Content Installed: No

**Comment by misterplus** [comment]
There's a 10 craft limit for each player, since this item was supposed to make early resource finding easy.
