### ISSUE TITLE
A3测试所需改动

### ISSUE THREAD

**Issue by misterplus** [misterplus/Levitated#16]
在下方评论需要改动的内容，格式为

- [ ] 内容描述

**Comment by Haocen2004** [comment]
- [ ] 蓝宝石红宝石进度
- [ ] 绿宝石获取方式
- [ ] 蒸馏器进度检查
- [ ] 无线终端 全 家 桶 ！

**Comment by misterplus** [comment]
- [ ] 下界/末地矿物统一问题/掉落问题

- [ ] 矿辞统一问题

**Comment by misterplus** [comment]
- [ ] topography不可用 重写mod

**Comment by misterplus** [comment]
- [ ] 补充tips

**Comment by misterplus** [comment]
- [ ] 添加陨石配方/生成

**Comment by misterplus** [comment]
添加i18n配置

**Comment by misterplus** [comment]
- [ ] 重做Deepmoblearning套装配方

**Comment by misterplus** [comment]
- [ ] 修复weather2配方

**Comment by misterplus** [comment]
- [ ] 添加陨石、水源相关成就

**Comment by misterplus** [comment]
- [ ] 提前运行blockdrops和jer并将文件放入zip
- [ ] 等待CMM的完工
