### ISSUE TITLE
[Bug] 采油进度触发bug

### ISSUE THREAD

**Issue by Haocen2004** [misterplus/Levitated#23]
## Bug描述

采油进度触发bug

### 在之前的版本中出现过此问题吗？

未知，起码a测正常？

## 重现Bug的步骤

建造完成采油机后进度未完成

## 日志

* 客户端/服务端日志:none
* 崩溃报告:none

## 客户端信息
* 模组包版本:1.2
* Java版本:1.8
* 启动器:mmc
* 分配内存:6400
* 服务器/局域网/单人游戏:server
* 是否安装Optifine:yes
* 是否安装光影:no

## 世界信息
* 创建世界时的模组包版本:1.0
* 安装的其他模组等额外内容:optifine

**Comment by misterplus** [comment]
Fixed! Thanks for reporting!
