### ISSUE TITLE
Netherending ores模组矿石无限经验掉落问题

### ISSUE THREAD

**Issue by 0Yimeng0** [misterplus/Levitated#33]
## Bug描述

使用集成动力的方块破坏口无法破坏该模组矿石。

在试图破坏该模组添加钻石矿,红石等掉落物附有经验的矿石，则会有经验掉落，而矿石本身无变化，以至于无限经验。

## 重现Bug的步骤

1.放置该模组钻石矿石;
2.设置集成动力的方块破坏口使其破坏该矿石;
3.重现完成。

## 客户端信息
* 模组包版本:Beta-1.3.2
* Java版本:jre 1.8.0_261
* 启动器:HMCL 3.3.173
* 分配内存:6144MB
* 服务器/局域网/单人游戏:单人游戏
* 是否安装Optifine:是
* 是否安装光影:否

## 世界信息
* 创建世界时的模组包版本:<
* 安装的其他模组等额外内容:jeiintegration, JustEnoughCharacters, MiniHUD

个人期望:  希望不要通过禁掉方块破坏口来解决此问题。

**Comment by misterplus** [comment]
在发issue的时候不需要删除占位符，删除掉会被识别为未按模板填写而自动关闭

**Comment by misterplus** [comment]
Closed via https://github.com/misterplus/Levitated/commit/524971057425d7583b03a04739df575a2dec3d33
