### ISSUE TITLE
unable to get a bottle of water the vanila way

### ISSUE THREAD

**Issue by dutch-gamer** [misterplus/Levitated#42]
## Bug Description
when i try to right click a cauldron with water in it or a water source block with a 'glass bottle' the only thing i get is an 'ender air bottle' from the mod 'botania', even wen completely submerged in watter source blocks.

### Did this behavior use to work in the previous version?
No

## Steps to Reproduce (for bugs)
1. be in the end dimension
2. hold a vanilla empty bottle and look at a water source block/filled cauldron within 4 blocks
3. right click

## Logs
...the game doesn't crash so no log

## Client Information
* Modpack Version: 1.4.0
* Java Version: jre 1.8.0
* Launcher Used: twitch
* Memory Allocated: 7.1GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in:1.3.? what ever came before 1.4.0 the iteration doesn't exist anymore
* Additional Content Installed: none

**Comment by misterplus** [comment]
You can use a fluid tank from Ender IO.
