### ISSUE TITLE
关于增加部分物品获取方式的一点设想

### ISSUE THREAD

**Issue by pandaducks** [misterplus/Levitated#48]
## 建议内容

目前游玩的版本是1.4.0-hotfix，进度是正在冲刺彩虹。
游玩过程中感觉有部分物品获取方式缺失/获取方式过于烦琐，主要是这些物品的来源大多都与mob有关。
首先是想做电弧炉的hop棒，靠挤压只能获得50%耐久的，想要100%的需要找IE特有的工程师村民购买蓝图。
其次是深度怪物学习的两个非原版生物的数据模型，一个是匠魂的蓝色史莱姆模型，另一个是热力的模型。
制作/激活模型均需要击杀匠魂特有的三种史莱姆/热力特有的暴雪/狂风/岩石人，他们的产物影响了匠魂的装备铭刻/热力信素以上的升级。
当然，我知道这些都不是必须的，比如hop棒是有渠道可以修复至100%的，匠魂史莱姆可以依靠粘滑词缀，热力生物可以去主世界等待自然生成。
（如果这确实是你们的设计意图，请当我没有来过这里）
我想提的建议是，考虑将这些mob的生成加入zen summoning的召唤配方里，让玩家通过支付一定的代价取得它们。
这样相对平衡但却不需要依赖繁琐的原版方法，希望你们能够接受。

## 配置/脚本文件 (与建议相关，且有能力提供时填写)

抱歉，我并不会zenscript，还是麻烦你们吧。
祝这个包成长得更好！

**Comment by misterplus** [comment]
https://github.com/misterplus/Levitated/commit/d0d70d4f027806bd91d2ff8a110efef405d2a3dc
