### ISSUE TITLE
Assembler crashes with inventory tweaks

### ISSUE THREAD

**Issue by Finn95** [misterplus/Levitated#51]
## Bug Description

 if you scroll refined steel into the assembler from extra utilities, it voids the item

### Did this behavior use to work in the previous version?

first time playing

## Steps to Reproduce (for bugs)

1.get refined steel
2. scroll it into assembler
3. it voids itself

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:1.4.1
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by misterplus** [comment]
Unfortunately this bug was caused by extra utilities itself, which stopped updating a long time ago, just be careful next time.
