### ISSUE TITLE
[Suggestion] Please add in an early unified storage option or a way to obtain a vanilla sapling.

### ISSUE THREAD

**Issue by DizzyDJW** [misterplus/Levitated#56]
## Context

[Simple Storage Networks](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network) would be a perfect early-game universal storage option, especially combined with any of the following: [Colossal Chests](https://www.curseforge.com/minecraft/mc-mods/colossal-chests), [CompactStorage](https://www.curseforge.com/minecraft/mc-mods/compactstorage), or some way to get a vanilla sapling early on to be able to utilize the Storage Drawers, as there is currently no way to obtain a storage drawer while waiting forever to get enough mana to craft a single Terrasteel Ingot.

If you can think of a more creative/niche mod that does the same thing, I'd be happy to use it, as Applied Energistics seems to be a long way off, and I have a base with too many chests.

## Config/Script Details (if desired)

Maybe using a menril sapling on the mana pool gets you an oak sapling?

**Comment by DizzyDJW** [comment]
Or something more creative, last minute thought, leaves, thrown into mana pool will get you oak leaves, which you'll have to break and hope for an oak sapling, to make it a tiny bit harder.

**Comment by Haocen2004** [comment]
Storage Drawers can be craft by dragonwood, try to search `@conttweak` in jei.

**Comment by misterplus** [comment]
Use framed drawers would be just fine, we're adding an advancement for that just in case ppl missed it.

**Comment by DizzyDJW** [comment]
Wyrmwood Trim is the only thing that shows up.
