### ISSUE TITLE
Nether Scanning voids existing liquids

### ISSUE THREAD

**Issue by Nidaelie** [misterplus/Levitated#61]
Beta version 1.5.0, freshly installed

## Bug Description
WIth the Scanner mod update previously started generation and/or already generated now glitches and the lava dissapear and other resources

### Did this behavior use to work in the previous version?
The previous version was not working correctly due to the absurd rf/t needed and the regeneration of chunks 

## Steps to Reproduce (for bugs)

1. start regenerating chunks in 1.4.1
2. update the pack to 1.5.0   beta
3. trying to follow the new added steps for this quest chain

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 1.5.0 beta
* Java Version: 1.8.0.261
* Launcher Used: gdl
* Memory Allocated: 8gb
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by misterplus** [comment]
I've addressed this issue more in the discord, please check it out. I believe this is not an issue on our part.

**Comment by misterplus** [comment]
About how the scanner is replacing existing lava with air, it does seem to be an issue on our part, we'll look into it, thanks for reporting.

**Comment by misterplus** [comment]
I've made a temp fix version of scanner, you can try swapping this with the existing 1.6.10.jar and see if rebuilding in the same chunk will consume the liquid or not.
[scanner-1.6.11.jar.zip](https://github.com/misterplus/Levitated/files/5345494/scanner-1.6.11.jar.zip)

**Comment by misterplus** [comment]
You may ran into some random gaps when generating the nether, here's why.
In the previous version(1.4.1), the scanner would skip building if the current block is non-air, which would create gaps with flowing liquids. It would also void the block in the remote dimension (the one that it moves blocks from) even if that block is skipped.
So in the newer version(1.5.0), if you would build in old chunks, it would try to copy everything over and only replace air AND non-source liquid blocks. But due to `It would also void the block in the remote dimension (the one that it moves blocks from) even if that block is skipped.`   It would copy the air over the flowing block, thus creating a gap.

If you would build new chunks in the new version(the fixed version, of course), everything should be well-connected.

**Comment by Nidaelie** [comment]
I just did a fresh install copied only the save and the journeymap... replaced the file u modified and not working.... the scanner seems stuck in a few blocks cycle and not regenerating correctly te lava.

Will try to remove the dim and start again 

Btw, im not the only one having the issue.... so let me doubt about a corrupt install

**Comment by Nidaelie** [comment]
Removed the dim... started again and the scanner cant regenerate a lot of chunks correctly... just poping a few lava sources, a few blocks and nothing more.... 
![2020-10-08_09 26 03](https://user-images.githubusercontent.com/31002746/95427760-58f9e700-0948-11eb-93a4-c9b0afd27bed.png)
![2020-10-08_09 26 11](https://user-images.githubusercontent.com/31002746/95427765-5ac3aa80-0948-11eb-9966-aa503f508675.png)

**Comment by Nidaelie** [comment]
In a lot of bugged chunks the scanner stuck in a few blocks cycle after "ending" the regen, from this point the chunk keeps bugged and cant regene in any way...

**Comment by misterplus** [comment]
> Removed the dim... started again and the scanner cant regenerate a lot of chunks correctly... just poping a few lava sources, a few blocks and nothing more....
> ![2020-10-08_09 26 03](https://user-images.githubusercontent.com/31002746/95427760-58f9e700-0948-11eb-93a4-c9b0afd27bed.png)
> ![2020-10-08_09 26 11](https://user-images.githubusercontent.com/31002746/95427765-5ac3aa80-0948-11eb-9966-aa503f508675.png)

That's because in the remote dimension the blocks are already removed, if you only removed dim-1, the remote dimension is still empty, you need to remove dim100 to regenerate.

**Comment by misterplus** [comment]
> In a lot of bugged chunks the scanner stuck in a few blocks cycle after "ending" the regen, from this point the chunk keeps bugged and cant regene in any way...

That is because you need to move the scanner to generate another chunk, waiting in place won't do you any good.

**Comment by Nidaelie** [comment]
with the queue block u dont need to mover every chunk

**Comment by misterplus** [comment]
> with the queue block u dont need to mover every chunk

I was talking about the scanner alone.

**Comment by misterplus** [comment]
If you want to still continue your previous world, I suggest removing dim-1 and dim100 so the scanner can find blocks to regenerate. Since the whole regenerate process is just moving a block from dim100 to dim-1(the nether that the player is in)

**Comment by Nidaelie** [comment]
> 
> 
> > with the queue block u dont need to mover every chunk
> 
> I was talking about the scanner alone. Also, you're never supposed to delete dim-1 (nether) and regenerate, that's not how the mod works. So this is not an issue on our part. Thousands of players already played ver 1.4.1, this won't be a random issue that just appears for you, that's not how mod works, you don't get a random issue because you did nothing.

Well a lot of people had this issue with 1.4.1 and u can check reddit for example...

Btw this is not the way to deal with an issue with your modpack... if i have an issue i go to the first source... the modpack i dont have to start navigating to the sources (the mod in this case) cause it is not my job, it is yours

And yes t is an issue in your part because it is your modpack, your configs and your code....

**Comment by Nidaelie** [comment]
> 
> 
> About how the scanner is replacing existing lava with air, it does seem to be an issue on our part, we'll look into it, thanks for reporting.

As u said this was an issue of your part... generating more issues in the regen....

**Comment by misterplus** [comment]
Reddit players are talking about how they cannot generate another chunk without moving the scanner, I've made my point very clear. In the new version of the scanner, the terrain scanner won't replace existing source blocks anymore. If you insist on continuing this question, I'll leave you be.

**Comment by misterplus** [comment]
The main issue has been resolved.

**Comment by Nidaelie** [comment]
pathetic way to deal with an issue, u cant deal with them, and if u are exposed u just need to remove player from discord

**Comment by misterplus** [comment]
![image](https://user-images.githubusercontent.com/40316318/95434195-8e6ff600-0983-11eb-91a3-1dafab39dbb3.png)
For anyone who thinks I'm impatient.
