### ISSUE TITLE
updated to HOTFIX 08/10/2020 causes game to crash in "InControl" module "spawnRules"

### ISSUE THREAD

**Issue by vizzair** [misterplus/Levitated#66]
## Bug Description
updated to HOTFIX 08/10/2020 causes game to crash in "InControl" module "spawnRules"

### Did this behavior use to work in the previous version?
yes v1.5.0

## Logs

https://pastebin.com/embed_js/04g9SFv0

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by misterplus** [comment]
You might wanna download the zip pack again and copy all files in "config/incontrol" over to your minecraft instance, I've tested compatiblity between versions and it works fine for me.

**Comment by vizzair** [comment]
yea that fixed it.
