### ISSUE TITLE
Missing Textures in content tweaker etc.

### ISSUE THREAD

**Issue by OniOnyx** [misterplus/Levitated#67]
## Bug Description

 Many textures are missing from a number of things, most notably Content Tweaker. I've done a fresh reinstall of Minecraft, forge, and Levitation a few times and still no textures are found. Is there a place I can find them to put in the folder or?

### Did this behavior use to work in the previous version?

 Textures were gone in all attempts.

## Steps to Reproduce (for bugs)

1. The custom main menu is missing textures too. But after entering a wold, searching content tweaker, for example, with an @ in front of it in JEI would show that every texture is gone.
2. All of the items associated with it and a couple mods here and there just have the magenta/black checkers. The quests are also missing textures and have weird names that look like code.
3. The folders where the textures would be are empty.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: latest
* Java Version: latest
* Launcher Used: Forge 1.12.2
* Memory Allocated: 6 gb
* Server/LAN/Single Player: Multiplayer using Aternos
* Optifine Installed: yes 1.12.2 version
* Shaders Enabled: none

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by misterplus** [comment]
Download the pack again and make sure you have downloaded the folder named "resources" which is included.

**Comment by OniOnyx** [comment]
The folder and the folders inside of resources downloads, but the actual content inside those folders is absent no matter how many times I download it.

**Comment by OniOnyx** [comment]
[resources.zip](https://github.com/misterplus/Levitated/files/5378502/resources.zip)
heres the folder that was in there, see the empty folders that came through with download. (note that the folder has 'copy,' it was just so i could transfer into .zip.)

**Comment by misterplus** [comment]
Then that's your network's issue, sorry, can't help you with that. You may try to download with a third party launcher like multimc

**Comment by OniOnyx** [comment]
Maybe I'm just downloading the wrong one. One pack download has things the other doesnt. The standard one shows 1.89 MB, the hotfix version shows 1.96 MB. Then the server one shows 189.89 MB, and the hotfix shows 193.40 MB. Which am I supposed to download if I'm playing on aternos? It runs 1.4.1.

**Comment by misterplus** [comment]
Do NOT download the serverpack then copy everything over, the serverpack does not contain client side resources like textures!!!!
