### ISSUE TITLE
关于匠魂末影钢特性direct会导致双倍矿物；

### ISSUE THREAD

**Issue by SiliconO** [misterplus/Levitated#70]
## Bug描述

1.使用带ender IO末影钢特性direct的稿子挖掘红石和青金石时会同时出现普通挖掘掉落的矿物和因特性直接传送到玩家背包的原矿；发现bug时已安装拼音搜索，但删除后依然存在
2.用鼠标滚轮向末影发电机里放珍珠会导致珍珠消失，用这种方式提供珍珠发电机里只会存在一个珍珠，其他放入的珍珠消失了，不是背包物品临时不显示的bug；这个bug在游玩途中突然出现，可能与jei拼音搜索有关，但删除后依然存在

## 在之前的版本中出现过此问题吗？

1.4.1版本，没有下载过其他版本

## 重现Bug的步骤

用带direct特性的稿子挖掘能直接产生掉落矿物的矿石，矿物正常掉落，原矿同时传送到背包获得双倍矿物
打开末影发电机的界面，用滚轮一个个放入珍珠，

## 日志

* 客户端/服务端日志:
* 崩溃报告:

## 客户端信息
* 模组包版本:1.4.1
* Java版本:1.8
* 启动器:hmcl
* 分配内存:8g
* 服务器/局域网/单人游戏:单人
* 是否安装Optifine:没有
* 是否安装光影:没有

## 世界信息
* 创建世界时的模组包版本:1.4.1
* 安装的其他模组等额外内容:jei拼音搜索

**Comment by SiliconO** [comment]
矿石的bug形成了循环能无限刷矿了

**Comment by misterplus** [comment]
1.5.0已经去除了所有带direct部件的配方了，EIO作者那边目前还没有反馈过，可以去反馈一下，与dropt模组不兼容。

**Comment by misterplus** [comment]
至于exu2的bug，老bug了，模组已经停更了，没有什么办法。
