### ISSUE TITLE
Integrated Dynamics advancements missing?

### ISSUE THREAD

**Issue by Quezler** [misterplus/Levitated#71]
## Bug Description

Integrated Dynamics doesn't show any advancements, so the rewards in the tutorial book you get are unclaimable.

(not sure if this is a bug or if its intentionally disabled, but i didn't notice any disabled settings in the config for the mod)

### Did this behavior use to work in the previous version?

unknown.

## Steps to Reproduce (for bugs)

1. use the advancement sync command with a friend thats shown in the exclamation mark. (possibly optional)
2. reach the integrated dynamics part of the quest line.
3. notice there are no advancements for it in the escape menu, and the reward sections in the book are empty above.

## Logs

* Client/Server Log: the one i have contains private data, but no integrated dynamics or advancement errors seem present.
* Crash Log: none.

## Client Information
* Modpack Version: Levitated-Beta-1.5.0-HOTFIX2
* Java Version: 1.8.0_161
* Launcher Used: twitch
* Memory Allocated: 8 gb
* Server/LAN/Single Player: server
* Optifine Installed: unknown
* Shaders Enabled: unknown

## World Information
* Modpack Version world created in: Levitated-Beta-1.5.0-HOTFIX2
* Additional Content Installed: none

**Comment by misterplus** [comment]
Ooops, forgot about that. I'll add that back in the next version, sorry about this.

**Comment by Quezler** [comment]
ah nice, glad to know it wasn't a mod issue or something intentionally disabled! ❤️

(is there a quick "change this and that" patch i can use for the server my and a friend play on by editing the files? 🤔)

**Comment by misterplus** [comment]
In config/triumph/Triumph.txt,
add the modid of integrateddynamics into this list
keepAdvancements(["botania", "tombstone", "pneumaticcraft", "integrateddynamics"])
Do this for the client and the server

**Comment by misterplus** [comment]
Closed via https://github.com/misterplus/Levitated/commit/1edb43811e6a5b89bb1923c108c2820d89adb318
