### ISSUE TITLE
用hmcl进入游戏后，加载游戏会崩溃

### ISSUE THREAD

**Issue by tianqo** [misterplus/Levitated#74]
## Bug描述

启动游戏，在forge页面加载到一半时游戏崩溃，显示非正常退出，运行内存给够了，电脑配置也不差

### 在之前的版本中出现过此问题吗？

在1.4.1版本也出现过这个问题

## 重现Bug的步骤

1.从curseforge下载zip压缩包
2.用hmcl自带整合包导入设置导入
3.设置需要运行内存（3G）
4.启动游戏

## 日志

* 客户端/服务端日志:https://paste.ubuntu.com/p/Njr5qwcTVY/
* 崩溃报告:https://paste.ubuntu.com/p/2N42fwbGmR/

## 客户端信息
* 模组包版本:1.5.0
* Java版本:java8
* 启动器:hmcl
* 分配内存:3072mb
* 服务器/局域网/单人游戏:单人游戏
* 是否安装Optifine:否
* 是否安装光影:否

## 世界信息
* 创建世界时的模组包版本:1.5.0
* 安装的其他模组等额外内容:无

**Comment by misterplus** [comment]
下载不全，3G太少，建议4G起步。
