### ISSUE TITLE
科技复兴mod的工业高炉无法正常制作碳酸钙

### ISSUE THREAD

**Issue by Jason-kiss** [misterplus/Levitated#76]
## Bug描述

在Bate1.5.0版本中，科技复兴mod中的工业高炉，在2200温度以上各种电压级别下，都无法使用空单元和矿渣（炉渣）制作碳酸钙单元。

### 在之前的版本中出现过此问题吗？

没玩过其他版本

## 重现Bug的步骤

1.搭建科技复兴mod的工业高炉，已尝试进阶机械方块和高级方块搭建。
2.供电。
3.尝试使用空单元和炉渣制作碳酸钙单元失败。

## 日志

* 客户端/服务端日志:
* 崩溃报告:
无

## 客户端信息
* 模组包版本:1.5.0
* Java版本:8
* 启动器:HCML
* 分配内存:8G
* 服务器/局域网/单人游戏:服务器&单人游戏
* 是否安装Optifine:没改动过，不知道
* 是否安装光影:无

## 世界信息
* 创建世界时的模组包版本:1.5.0
* 安装的其他模组等额外内容:无

**Comment by misterplus** [comment]
#72 1.5.1已经修复。
