### ISSUE TITLE
[所反馈Bug的简要描述]

### ISSUE THREAD

**Issue by s99889989** [misterplus/Levitated#77]
## Bug描述

伺服器crash

## 重现Bug的步骤

1.
2.
3.

## 日志

* 客户端/服务端日志:
* 崩溃报告:https://pastebin.com/5icc35Nu

## 客户端信息
* 模组包版本:1.5.1
* Java版本:Java8 Update 261 (64-bit)
* 启动器: 
* 分配内存: -Xms15G -Xmx15G
* 服务器/局域网/单人游戏: 服务器
* 是否安装Optifine:
* 是否安装光影:

## 世界信息
* 创建世界时的模组包版本: 1.5.1
* 安装的其他模组等额外内容: authmod-2.6和dcintegration-1.1.18-1.12

**Comment by Haocen2004** [comment]
疑似是玩家跑图时候导致实体加载错误引发了watchdog  
可以尝试下清一下末影人  
建议发送latest.log辅助我们分析问题

**Comment by misterplus** [comment]
建议提供crash时的其他信息

**Comment by s99889989** [comment]
OK 如有崩潰  我在連log都附上
