### ISSUE TITLE
Warpcore Multiblock issue.

### ISSUE THREAD

**Issue by Zetsumeinaito** [misterplus/Levitated#78]
I updated recently and tried to make the warp core multiblock. it didn't work out. 

Looking closely it wanted Vulpes "Titanium Blocks" only. Those are uncraftable. What I have are tech reborn Blocks of Titanium. And those don't work as a replacement. Tried going creative, and they are still unavailable. 

I assume some config somewhere was updated incorrectly as I saw in Isaac's(GamingOnCaffeine) video, his server used the old version and the multiblock for the warp core flashed between both tech reborn and Vulpes versions, Meaning the old version accepted either titanium blocks, while the current one accepts a phased out version,

If it's just me, could I get directions on how to fix the correct config file?

**Comment by misterplus** [comment]
Are you sure titanium blocks from TR won't work? We didn't do any change to that specific part of the config. It'll take me a couple more hours to go back home and check tho.

**Comment by misterplus** [comment]
Hmm, seems like it doesn't work for some reason. We did not change any config related to this, this might be an issue due to a mod update, I'll do some debugging for now and push a hotfix asap.

**Comment by misterplus** [comment]
I've located the issue, it's due to a feature change in Advanced Rocketry.
You can downgrade to AdvancedRocketry-1.12.2-1.7.0-231-universal.jar to solve the issue temporarily.
I'll work on a hotfix now.

**Comment by misterplus** [comment]
https://www.curseforge.com/minecraft/modpacks/levitated/files/3096983
Hotfix is out, downgrading ar like I said above also works.

**Comment by Zetsumeinaito** [comment]
sweet, thanks for the save mate.
