### ISSUE TITLE
“双锂晶体”成就不能解锁

### ISSUE THREAD

**Issue by Jason-kiss** [misterplus/Levitated#79]
## Bug描述

无法通过获取、捡起、打碎双锂矿石和双锂晶体来解锁“双锂晶体”成就

### 在之前的版本中出现过此问题吗？

不知

## 重现Bug的步骤

1.
2.
3.

## 日志

* 客户端/服务端日志:
* 崩溃报告:

## 客户端信息
* 模组包版本:1.5.1
* Java版本:8
* 启动器:HCML
* 分配内存:8G
* 服务器/局域网/单人游戏:服务器
* 是否安装Optifine:
* 是否安装光影:

## 世界信息
* 创建世界时的模组包版本:
* 安装的其他模组等额外内容:

**Comment by misterplus** [comment]
看了下，代码没什么问题
不愧是triumph，bug的王
