### ISSUE TITLE
[所反馈Bug的简要描述]

### ISSUE THREAD

**Issue by Misaka-master** [misterplus/Levitated#80]
## Bug描述

为什么只加了CustomSkinLoader(皮肤),JustEnoughCharacters(Jei拼音搜索),itemscroller(鼠标手势)这三个mod就崩了

把这几个mod去掉又可以正常启动

## 重现Bug的步骤

1.
2.
3.

## 日志

* 客户端/服务端日志:
* 崩溃报告:https://paste.ubuntu.com/p/nrj7C2Xf98/

## 客户端信息
* 模组包版本:1.5.1
* Java版本:8
* 启动器:HMCL
* 分配内存:8G
* 服务器/局域网/单人游戏:
* 是否安装Optifine:是
* 是否安装光影:

## 世界信息
* 创建世界时的模组包版本:
* 安装的其他模组等额外内容:

**Comment by misterplus** [comment]
itemscroller不加，加另外两者能正常启动吗

**Comment by misterplus** [comment]
添加mod建议一个一个来，而且还是在有optifine的情况下。

**Comment by Misaka-master** [comment]
查出来了,是那个接拼音搜索的问题
不过这个mod为什么会有问题呢

**Comment by misterplus** [comment]
> 查出来了,是那个jei拼音搜索的问题
> 不过这个mod为什么会有问题呢

建议使用最新版本，并且确认是1.12.2的版本

**Comment by Misaka-master** [comment]
> > 查出来了,是那个jei拼音搜索的问题
> > 不过这个mod为什么会有问题呢
> 
> 建议使用最新版本，并且确认是1.12.2的版本

呃,就是最新版的

**Comment by Misaka-master** [comment]
ok了,3.4.3版本的就能启动了
