### ISSUE TITLE
装配机吞材料

### ISSUE THREAD

**Issue by Control-Core** [misterplus/Levitated#82]
## Bug描述

装配机在材料没有到堆叠上限时直接往机器里添加材料会直接消失，并不会叠加进原本的材料组里面

## 重现Bug的步骤

1.放置装配机
2.在装配机里面添加没有到堆叠上限的材料
3.对没有到堆叠上限的材料进行补充

## 日志

* 客户端/服务端日志:
* 崩溃报告:

## 客户端信息
* 模组包版本:1.5.1hotfix
* Java版本:jre1.8.0_231
* 启动器:Multimc5 0.6.11-1430
* 分配内存: 9216mb
* 服务器/局域网/单人游戏:单人游戏
* 是否安装Optifine:无
* 是否安装光影:无

## 世界信息
* 创建世界时的模组包版本:1.4.1
* 安装的其他模组等额外内容:中文汉化资源包

**Comment by misterplus** [comment]
exu2已经停更了，老bug了，修不成
只能用的时候小心一点了。
