### ISSUE TITLE
无法创建世界

### ISSUE THREAD

**Issue by Misaka-master** [misterplus/Levitated#85]
## Bug描述

在仅安装optifine的情况下,进入游戏,更改设置后单人游戏创建世界时会卡在"加载世界中".
如果退出游戏再进入之前创建的那个世界也是这样卡住
卡住时关游戏会出来一个"尝试还原此程序",点了后会卡住"0%"

### 在之前的版本中出现过此问题吗？

1.5.1-hotfix也是这样

## 重现Bug的步骤

1.
2.
3.

## 日志

* 客户端/服务端日志:
* 崩溃报告:

## 客户端信息
* 模组包版本:1.5.2
* Java版本:8
* 启动器:HMCL
* 分配内存:8
* 服务器/局域网/单人游戏:单人游戏
* 是否安装Optifine:是
* 是否安装光影:内置光影

## 世界信息
* 创建世界时的模组包版本:
* 安装的其他模组等额外内容:无

**Comment by misterplus** [comment]
不安装optifine的情况下能创建吗，如果可以请更换optifine版本后重试。

**Comment by Misaka-master** [comment]
删除optifine和更换版本都不起效

**Comment by misterplus** [comment]
所以到底是卡了多久，CPU主频是？

**Comment by Misaka-master** [comment]
最后就是会卡在0%,放了一两个小时也没反应
CPU是intel的Xeon e5-2650 
周末有空再试试能不能玩吧

**Comment by Misaka-master** [comment]
![image](https://user-images.githubusercontent.com/67221027/99259205-9f4e3a00-2854-11eb-9d0c-ac02711c886a.png)
就是这样的情况,底下的字会变但是进不去

**Comment by misterplus** [comment]
无法重现。
