### ISSUE TITLE
Fel Pumpkin removal makes Cocoon impossible to craft

### ISSUE THREAD

**Issue by klugemonkey** [misterplus/Levitated#86]
## Bug Description
Removal of Fel Pumpkin makes it impossible to craft Cocoon.

### Did this behavior use to work in the previous version?
Yes.

## Steps to Reproduce (for bugs)
1.  Try to craft Cocoon, it will require Fel Pumpkin
2.  Try to craft Fel Pumpkin, it was removed.

## Logs
N/A

## Client Information
* Modpack Version: 1.5.2
* Java Version: N/A
* Launcher Used: N/A
* Memory Allocated: N/A
* Server/LAN/Single Player: N/A
* Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information
* Modpack Version world created in: 1.5.1-HOTFIX
* Additional Content Installed: None

**Comment by misterplus** [comment]
What exactly do you need Cocoon for? We've provided most of the summonables in the summoning alter.

**Comment by klugemonkey** [comment]
Ah, well, if that's the case then just need to remove it as well in botania.zs.   I do like the surprise nature of the cocoon though.  Not sure entirely what you will get.

**Comment by klugemonkey** [comment]
What was the reason for the removal of the pumpkin?

**Comment by misterplus** [comment]
> What was the reason for the removal of the pumpkin?

You can get blaze powder early in the end, thus skipping part of the progression. While not being game-breaking, this does hurt the flavor quite a bit.
