### ISSUE TITLE
Monster jerky uncraftable

### ISSUE THREAD

**Issue by wickedsharp** [misterplus/Levitated#87]
## Bug Description

Monster jerky is uncraftable with wisdom wood drying racks. No other options to craft it without access to oak wood. With jerky being needed to summon a cow for milk to run the slimey gen to run the rainbow gen to get to the overworld, this is unworkable. 

### Did this behavior use to work in the previous version?

?

## Steps to Reproduce (for bugs)

1. Need monster jerky
2. Try to craft it on wisdom wood drying rack
3. Nothing happens

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 1.5.2
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in: 
* Additional Content Installed:

**Comment by misterplus** [comment]
You can craft drying racks with other wood types, wisdom wood for example.

**Comment by wickedsharp** [comment]
Wisdom wood drying racks don't work.

**Comment by wickedsharp** [comment]
Making lavawood doesn't seem possible either, as there's nothing listed that can bre smelted to make lava and placing lava directly into the smelter doesn't work.

**Comment by wickedsharp** [comment]
Okay. IAMTA here. I made an item rack with the wisdom wood, not a drying rack.
