### ISSUE TITLE
平成之梦无法正常使用

### ISSUE THREAD

**Issue by todaysunnynoon** [misterplus/Levitated#89]
## Bug描述

平成之梦无法正常使用

### 在之前的版本中出现过此问题吗？

无

## 重现Bug的步骤

无
1.
2.
3.

## 日志

* 客户端/服务端日志:无
* 崩溃报告:无

## 客户端信息
* 模组包版本:1.5.2
* Java版本:8
* 启动器:pcl
* 分配内存:8000
* 服务器/局域网/单人游戏:
* 是否安装Optifine:无
* 是否安装光影:无

## 世界信息
* 创建世界时的模组包版本:1.5.2
* 安装的其他模组等额外内容:无

**Comment by todaysunnynoon** [comment]
服务器

**Comment by misterplus** [comment]
无法使用的意思是？

**Comment by misterplus** [comment]
长期无回复，且本问题不应存在，关了。
