### ISSUE TITLE
endstone mattock doesn't drop wyrmwood

### ISSUE THREAD

**Issue by longneck** [misterplus/Levitated#90]
## Bug Description

An endstone Tinker's Mattock doesn't drop Wyrmwood when chopping down a Wyrmwood tree.

### Did this behavior use to work in the previous version?

I have not tested on other versions.

## Steps to Reproduce (for bugs)

1. Craft an Endstone Mattock.
2. Chop down a Wyrmwood tree.
3. Observe no blocks dropped.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:1.5.2
* Java Version:1.8.0.51
* Launcher Used:Native
* Memory Allocated:8 GB
* Server/LAN/Single Player:Single Player
* Optifine Installed:No
* Shaders Enabled:None

## World Information
* Modpack Version world created in:1.5.2
* Additional Content Installed:None

**Comment by misterplus** [comment]
Fixed in the upcoming version 1.5.3
