### ISSUE TITLE
Redstone conduits

### ISSUE THREAD

**Issue by Rikkochi** [misterplus/Levitated#91]
Redstone conduits don't connect to lever or redstone lamp, wrench don't help too.
![2020-12-04_20 29 20](https://user-images.githubusercontent.com/75507804/101225413-27fc1100-3670-11eb-85c0-cf3a922dce72.png)

**Comment by misterplus** [comment]
These are redstone alloy POWER cables, you should be looking the other cable that has redstone in its name.
