### ISSUE TITLE
Implosion compressor multiblock not recognized

### ISSUE THREAD

**Issue by wickedsharp** [misterplus/Levitated#92]
## Bug Description

Even with the multiblock formed correctly per the hologram and the techreborn wiki, the implosion compressor continues to say 'incomplete multiblock'.

I don't know if this is a modpack issue or a techreborn issue but trying to update just techreborn just caused a crash.

### Did this behavior use to work in the previous version?

I assume it worked at some point?

## Steps to Reproduce (for bugs)

1. Craft implosion compressor and 26 advanced machine casings
2. Place implosion compressor, toggle multiblock hologram, and place advanced machine casings accordingly
3. Implosion compressor still says 'incomplete multiblock'

Repeated the process in creative with the same incomplete result.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:latest
* Java Version:
* Launcher Used:curseforge/overwolf
* Memory Allocated:
* Server/LAN/Single Player: single player
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by misterplus** [comment]
Can't reproduce, any screenshots?

**Comment by wickedsharp** [comment]
I did more experimenting and research and figured out that what the modpack calls 'advanced' machine casings is what the tech reborn wiki calls 'industrial' and the pack's 'reinforced' is the wiki's 'advanced'. This was really confusing and frustrating, bc the advanced/industrial ones are so very much more expensive to make.
