### ISSUE TITLE
[植物魔法遗物无法获取]

### ISSUE THREAD

**Issue by reserveword** [misterplus/Levitated#93]
## Bug描述

两个玩家加入同一个队伍，其中一个玩家打败盖亚2并获取遗物后，另一个玩家就无法获取同一遗物

### 在之前的版本中出现过此问题吗？

没玩过别的版本

## 重现Bug的步骤

1. 创建服务器和两个玩家
2. 让两个玩家加入同一队伍
3. 一个玩家使用命运骰子，获取全部六种遗物
4. 两个玩家同步进度
5. 另一个玩家使用命运骰子，不能获取任何遗物（骰子停留在x上，然后就消失了）

## 日志

* 客户端/服务端日志:
* 崩溃报告:
N/A

## 客户端信息
* 模组包版本:1.5.2
* Java版本:1.8
* 启动器:HMCL
* 分配内存:6G
* 服务器/局域网/单人游戏:服务器
* 是否安装Optifine:是
* 是否安装光影:否

## 世界信息
* 创建世界时的模组包版本:1.5.2
* 安装的其他模组等额外内容:无

**Comment by misterplus** [comment]
无法修复，植魔特性。同步成就模组也没有提供黑名单的选项。

**Comment by reserveword** [comment]
能不能当一个人获取该遗物的时候同时给其他人也发一份同样的遗物？
