### ISSUE TITLE
Can't Enter Nether through Glitched Nether Portal Anymore

### ISSUE THREAD

**Issue by MCbecorn** [misterplus/Levitated#94]
## Bug Description

I have built the glitched nether portal and have been generating chunks for a while now.  One time I went into the nether, exited the game, opened it back up, went back to my base in the end to craft some stuff with a wither skull, went to go back into the nether, but nothing happened.  When I stand in the portal, it does the swirling animation but doesn't teleport me into the nether.  I also noticed that after finding this, my journeymap waypoints no longer worked, and I had to reset my spawn.  There aren't many places to look for help, since it is a custom portal for the modpack.  Portals still work in vanilla, but vanilla solutions have had no success.

### Did this behavior use to work in the previous version?

The portal has always worked before, and I didn't change any settings in the mod, the game, or my computer.  I deleted and redownloaded the modpack, still didn't work.  I made a new world, and it still didn't work.

## Steps to Reproduce (for bugs)

1. Enter nether portal
2. Restart game
3. Leave the nether

## Logs

* Client/Server Log:none
* Crash Log:none

## Client Information
* Modpack Version:1.5.2
* Java Version:latest
* Launcher Used:CurseForge
* Memory Allocated:8GB
* Server/LAN/Single Player:Singleplayer
* Optifine Installed:none
* Shaders Enabled:none

## World Information
* Modpack Version world created in:1.5.2
* Additional Content Installed:none

**Comment by misterplus** [comment]
You can right click with the tome of the underrealm again. This is a bug with gamestages where you lose some stages when the game crashes.

**Comment by MCbecorn** [comment]
That worked!  Even kept all of my previous progress.  Thanks for the help, keep up the good work.
