### ISSUE TITLE
Problems encoutered when using fallen kanade

### ISSUE THREAD

**Issue by Argey2000** [misterplus/Levitated#95]
## Bug Description
Fallen kanade doesn't function with mana supply.

### Did this behavior use to work in the previous version?
I haven't played the previous version, sorry for that.

## Steps to Reproduce (for bugs)
1. Place the fallen kanade
2. Connect it with a mana pool
3. Doesn't give players regen buff
![2020-12-11](https://user-images.githubusercontent.com/45259801/101887131-685f1000-3bd7-11eb-93a0-761383bca6b5.png)
![2020-12-11 (1)](https://user-images.githubusercontent.com/45259801/101887154-6e54f100-3bd7-11eb-9197-55323125f6db.png)
![2020-12-11 (2)](https://user-images.githubusercontent.com/45259801/101887167-714fe180-3bd7-11eb-8add-8faa976ac95c.png)
Note that the mana pool is the everlasting mana pool. The whole process is tested in gamemode 1.

## Logs
No crash here.

## Client Information
* Modpack Version:1.5.2
* Java Version:1.8.0_221
* Launcher Used:hmcl 3.3.170
* Memory Allocated: 4096mb
* Server/LAN/Single Player: single
* Optifine Installed: According to your pack default setting
* Shaders Enabled:  According to your pack default setting

## World Information
* Modpack Version world created in: Default (Void world or something)
* Additional Content Installed: No

**Comment by misterplus** [comment]
Not our issue, report to botania's author instead.
