### ISSUE TITLE
能否改进任务系统？

### ISSUE THREAD

**Issue by YogurtZebra** [misterplus/Levitated#97]
~~开发者也是中国人我就不用英语了~~

## 建议内容

能否对任务系统进行改进？MC自带的进度系统其实有点拉跨，也不是很方便，而且界面也很小，翻个任务要翻半天
其次，开局时的有的任务描述相对来说不是很详细，有的东西不知道去哪找，翻植魔的词典也要找老半天
~~其实最主要是没有任务奖励~~

## 配置/脚本文件 (与建议相关，且有能力提供时填写)

~~填这里好像不太对，但是管他呢~~

[Craft to Exile](https://github.com/mahjerion/Craft-to-Exile-Dissonance)整合包中的任务系统就很不错，貌似用的是[ftb-quests](https://minecraft.curseforge.com/projects/ftb-quests)，还有个前置模组[ftblib](https://minecraft.curseforge.com/projects/ftblib)

示例如下
![2020-12-13_084901](https://user-images.githubusercontent.com/57581480/102000759-aa966780-3d25-11eb-8b24-652fd34b8b4a.png)
![2020-12-13_084928](https://user-images.githubusercontent.com/57581480/102000761-ad915800-3d25-11eb-9af5-9d4ca70c06d3.png)

**Comment by misterplus** [comment]
首先进度系统没有问题，说进度系统和任务系统比不好，那咋不去找sevtech作者呢。
齐次，本包的进度本就是朝着朦胧的方向设计的，只是给你必要的信息，不是教你玩模组的。

**Comment by misterplus** [comment]
再说了，在进度已经完全设置好的情况下让作者用别的模组重写一遍？天方夜谭吧。
