### ISSUE TITLE
Unable to install modpack from twitch

### ISSUE THREAD

**Issue by AR-E** [misterplus/Levitated#98]
## Bug Description

 
Unable to install with the error message "This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 61811." I believe this is due to one of the mods in this pack being removed from CurseForge or something similar.

### Did this behavior use to work in the previous version?

I believe this issue is unrelated to modpack verision, but rather to mods present in the modpack.

## Steps to Reproduce (for bugs)

1. Try to install pack from twitch
2. Get error message

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information
* Modpack Version: Levitated-1.5.2
* Java Version: N/A
* Launcher Used: N/A
* Memory Allocated: N/A
* Server/LAN/Single Player: N/A
* Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information
* Modpack Version world created in: N/A
* Additional Content Installed: N/A

**Comment by AR-E** [comment]
I managed to install the modpack by downloading the zip from CurseForge and them importing it into MultiMC.

**Comment by misterplus** [comment]
The twitch client is being deprecated since the curseforge site is being transferred to overwolf, use the new curse client instead.

**Comment by AR-E** [comment]
Right, that was an error on my part. It's not the Twitch client but rather the CurseForge one that was giving me this issue.

**Comment by AR-E** [comment]
> The twitch client is being deprecated since the curseforge site is being transferred to overwolf, use the new curse client instead.

Right, that was an error on my part. It's not the Twitch client but rather the CurseForge one that was giving me this issue.
