### ISSUE TITLE
混沌珍珠有时无法正常合成

### ISSUE THREAD

**Issue by polarisR** [misterplus/Levitated#99]
## Bug描述

首先感谢作者的劳动，我非常喜欢失重这个整合包，但我最近遇到了混沌珍珠无法正常合成的问题，即把末影珍珠和末地石碎片放到合成栏（合成台也试过）之后，右边的产物栏不出现混沌珍珠的问题，此问题是偶然产生，也曾遇到过产物栏出现混沌珍珠但是无法取出的问题。也怀疑过是服务器网络问题，但在发生问题的同时，其他合成均能正常使用，模组可以正常游玩，所以应该不是网络问题。

### 在之前的版本中出现过此问题吗？

我是新玩家，没有玩过之前版本

## 重现Bug的步骤

因为是突然出现的问题，所以无法保证重现，只能上传bug截图
![image](https://user-images.githubusercontent.com/43192024/102159357-596dab80-3ebe-11eb-8585-84fcbe557d60.png)
视频：https://www.bilibili.com/video/BV1tV411h7NW

## 日志

* 客户端/服务端日志:无
* 崩溃报告:无崩溃问题

## 客户端信息
* 模组包版本:1.5.2
* Java版本: java8 64位
* 启动器:HMCL 3.3.163
* 分配内存:4096MB
* 服务器/局域网/单人游戏:服务器
* 是否安装Optifine:是
* 是否安装光影: 否

## 世界信息
* 创建世界时的模组包版本: 1.5.2
* 安装的其他模组等额外内容:无

**Comment by polarisR** [comment]
为了更好地展示此bug，我将bug的过程录制成了视频：
[https://www.bilibili.com/video/BV1tV411h7NW](url)

**Comment by polarisR** [comment]
问了别人好像是一个人只能用10次，我懂了

**Comment by misterplus** [comment]
咱但凡看一次JEI也不会问出这个问题
